project_id = "tablero"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
major_version = 17

[studio]
enabled = true
port = 55323

[local_smtp]
enabled = true
port = 55324
smtp_port = 55325
pop3_port = 55326

[analytics]
enabled = true
port = 55327

[db.pooler]
enabled = false
port = 55329

[auth]
enabled = true
site_url = "https://portal-seguimiento.vercel.app"
additional_redirect_urls = [
  "http://localhost:3000",
  "https://portal-seguimiento-miguel-maidanas-projects.vercel.app",
  "https://portal-seguimiento-git-main-miguel-maidanas-projects.vercel.app",
]
enable_signup = false
